# TeraiNet inference example

Follow [mewc-predict](https://github.com/zaandahl/mewc-predict/blob/main/src/mewc_predict.py) for the general procedure

## Setup

### Imports

Follow [mewc-flow](https://github.com/zaandahl/mewc-flow/blob/main/requirements.txt) for the key package versions

In [1]:
!pip install keras==3.3.3 kimm==0.2.5 tensorflow==2.16.1

Requirement already satisfied: keras==3.3.3 in /opt/conda/lib/python3.10/site-packages (3.3.3)
Collecting kimm==0.2.5
  Downloading kimm-0.2.5-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: tensorflow==2.16.1 in /opt/conda/lib/python3.10/site-packages (2.16.1)
Requirement already satisfied: absl-py in /opt/conda/lib/python3.10/site-packages (from keras==3.3.3) (1.4.0)
Requirement already satisfied: numpy in /opt/conda/lib/python3.10/site-packages (from keras==3.3.3) (1.26.4)
Requirement already satisfied: rich in /opt/conda/lib/python3.10/site-packages (from keras==3.3.3) (13.7.1)
Requirement already satisfied: namex in /opt/conda/lib/python3.10/site-packages (from keras==3.3.3) (0.0.8)
Requirement already satisfied: h5py in /opt/conda/lib/python3.10/site-packages (from keras==3.3.3) (3.11.0)
Requirement already satisfied: optree in /opt/conda/lib/python3.10/site-packages (from keras==3.3.3) (0.11.0)
Requirement already satisfied: ml-dtypes in /opt/conda/lib/python3.10/site-packages (from keras==3.3.3) (0.5.0)
Requirement already satisfied: astunparse>=1.6.0 in /opt/conda/lib/python3.10/site-packages (from tensorflow==2.16.1) (1.6.3)
Requirement already satisfied: flatbuffers>=23.5.26 in /opt/conda/lib/python3.10/site-packages (from tensorflow==2.16.1) (24.3.25)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /opt/conda/lib/python3.10/site-packages (from tensorflow==2.16.1) (0.5.4)
Requirement already satisfied: google-pasta>=0.1.1 in /opt/conda/lib/python3.10/site-packages (from tensorflow==2.16.1) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /opt/conda/lib/python3.10/site-packages (from tensorflow==2.16.1) (18.1.1)
Collecting ml-dtypes (from keras==3.3.3)
  Downloading ml_dtypes-0.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)
Requirement already satisfied: opt-einsum>=2.3.2 in /opt/conda/lib/python3.10/site-packages (from tensorflow==2.16.1) (3.3.0)
Requirement already satisfied: packaging in /opt/conda/lib/python3.10/site-packages (from tensorflow==2.16.1) (21.3)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /opt/conda/lib/python3.10/site-packages (from tensorflow==2.16.1) (3.20.3)
Requirement already satisfied: requests<3,>=2.21.0 in /opt/conda/lib/python3.10/site-packages (from tensorflow==2.16.1) (2.32.3)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.10/site-packages (from tensorflow==2.16.1) (70.0.0)
Requirement already satisfied: six>=1.12.0 in /opt/conda/lib/python3.10/site-packages (from tensorflow==2.16.1) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in /opt/conda/lib/python3.10/site-packages (from tensorflow==2.16.1) (2.4.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /opt/conda/lib/python3.10/site-packages (from tensorflow==2.16.1) (4.12.2)
Requirement already satisfied: wrapt>=1.11.0 in /opt/conda/lib/python3.10/site-packages (from tensorflow==2.16.1) (1.16.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /opt/conda/lib/python3.10/site-packages (from tensorflow==2.16.1) (1.64.1)
Requirement already satisfied: tensorboard<2.17,>=2.16 in /opt/conda/lib/python3.10/site-packages (from tensorflow==2.16.1) (2.16.2)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /opt/conda/lib/python3.10/site-packages (from tensorflow==2.16.1) (0.37.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /opt/conda/lib/python3.10/site-packages (from astunparse>=1.6.0->tensorflow==2.16.1) (0.43.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorflow==2.16.1) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorflow==2.16.1) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorflow==2.16.1) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorflow==2.16.1) (2024.6.2)
Requirement already satisfied: markdown>=2.6.8 in /opt/conda/lib/python3.10/site-packages (from tensorboard<2.17,>=2.16->tensorflow==2.16.1) (3.6)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /opt/conda/lib/python3.10/site-packages (from tensorboard<2.17,>=2.16->tensorflow==2.16.1) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /opt/conda/lib/python3.10/site-packages (from tensorboard<2.17,>=2.16->tensorflow==2.16.1) (3.1.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/conda/lib/python3.10/site-packages (from packaging->tensorflow==2.16.1) (3.1.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/conda/lib/python3.10/site-packages (from rich->keras==3.3.3) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/conda/lib/python3.10/site-packages (from rich->keras==3.3.3) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in /opt/conda/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich->keras==3.3.3) (0.1.2)
Requirement already satisfied: MarkupSafe>=2.1.1 in /opt/conda/lib/python3.10/site-packages (from werkzeug>=1.0.1->tensorboard<2.17,>=2.16->tensorflow==2.16.1) (2.1.5)
Downloading kimm-0.2.5-py3-none-any.whl (123 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.4/123.4 kB 3.2 MB/s eta 0:00:0000:01
Downloading ml_dtypes-0.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 34.5 MB/s eta 0:00:00a 0:00:01
Installing collected packages: ml-dtypes, kimm
  Attempting uninstall: ml-dtypes
    Found existing installation: ml_dtypes 0.5.0
    Uninstalling ml_dtypes-0.5.0:
      Successfully uninstalled ml_dtypes-0.5.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jax 0.4.35 requires ml-dtypes>=0.4.0, but you have ml-dtypes 0.3.2 which is incompatible.
Successfully installed kimm-0.2.5 ml-dtypes-0.3.2

In [2]:
import os
import yaml
import random
import shutil
import pandas as pd
from pathlib import Path

import kimm
import tensorflow as tf
from keras import saving

### Utilities

In [3]:
def copy_random_images(src_dir, dst_dir, n, seed=42):
    """
    Copies n random images from src_dir to dst_dir.

    Args:
        src_dir (str): Source directory containing images.
        dst_dir (str): Destination directory to copy images into.
        n (int): Number of images to copy.
        seed (int): Random seed for reproducibility.
    """
    # Ensure target directory exists
    os.makedirs(dst_dir, exist_ok=True)

    # List all files in the source directory
    all_files = [f for f in os.listdir(src_dir) if os.path.isfile(os.path.join(src_dir, f))]

    # Check if n is greater than available files
    if n > len(all_files):
        raise ValueError(f"Requested {n} images, but only {len(all_files)} available in source directory.")

    # Randomly sample n files
    random.seed(seed)
    selected_files = random.sample(all_files, n)

    # Copy each file to the target directory
    for filename in selected_files:
        src_path = os.path.join(src_dir, filename)
        dst_path = os.path.join(dst_dir, filename)
        shutil.copy2(src_path, dst_path)

    print(f"Copied {n} random images from '{src_dir}' to '{dst_dir}'.")

## Prepare images

In [4]:
copy_random_images("../input/preprocess-images/terainet_images/test2/class_1", "../images", 10)

Copied 10 random images from '../input/preprocess-images/terainet_images/test2/class_1' to '../images'.

In [5]:
img_generator = tf.keras.preprocessing.image_dataset_from_directory(
    "../images", 
    labels=None,
    label_mode=None,
    batch_size=8, 
    image_size=(224, 224),
    shuffle=False
)

Found 10 files.

## Predict

In [6]:
model = saving.load_model("../input/train-and-evaluate-terainet/model.keras", compile=False)

In [7]:
preds = model.predict(img_generator)

2/2 ━━━━━━━━━━━━━━━━━━━━ 14s 7s/step

In [8]:
preds

array([[5.2381847e-02, 1.9996221e-01, 2.8495291e-01, 4.6548069e-02,
        1.1974893e-01, 1.3221885e-01, 1.8170491e-02, 5.3616375e-02,
        5.2950364e-02, 3.9450005e-02],
       [2.5736994e-01, 1.0949787e-01, 1.6122012e-01, 1.3590532e-02,
        8.4038295e-02, 6.8595107e-03, 8.9867301e-03, 7.5156413e-02,
        6.8466127e-02, 2.1481442e-01],
       [1.9459581e-02, 1.6660877e-02, 9.0841949e-02, 1.2797284e-01,
        1.3810986e-01, 3.7299789e-02, 7.0161916e-02, 1.2626718e-01,
        3.3128676e-01, 4.1939180e-02],
       [7.7461773e-01, 7.5880433e-03, 8.1880882e-02, 4.1598991e-02,
        9.0330606e-03, 1.7620470e-02, 2.0352520e-02, 1.9009238e-02,
        8.6090667e-03, 1.9689834e-02],
       [8.7063599e-01, 5.8444124e-03, 5.6552164e-02, 1.0452784e-02,
        1.8009124e-02, 5.6710229e-03, 5.4316991e-03, 1.3848719e-02,
        6.1928863e-03, 7.3611112e-03],
       [8.0514151e-01, 1.4395743e-02, 8.6553395e-02, 2.4525946e-02,
        3.9340876e-02, 7.6304758e-03, 5.0827600e-03, 1.0611926e-02,
        1.8871448e-03, 4.8302752e-03],
       [7.6144505e-01, 8.4025208e-03, 1.0751269e-01, 1.1575127e-02,
        4.3309674e-02, 2.7876110e-03, 6.5608490e-03, 1.2849196e-02,
        1.8586205e-02, 2.6971122e-02],
       [1.7088867e-04, 9.5210455e-02, 1.5716454e-02, 1.3282196e-01,
        3.9729133e-01, 1.9458812e-02, 2.6046970e-01, 3.6439538e-02,
        1.5256525e-03, 4.0895283e-02],
       [8.8100767e-01, 1.2953432e-02, 1.5561954e-02, 4.5176274e-03,
        3.5792213e-02, 1.1688101e-03, 1.9974122e-03, 9.3817031e-03,
        1.1631563e-02, 2.5987720e-02],
       [8.5642254e-01, 1.3068046e-02, 2.1370009e-02, 2.7417492e-03,
        5.1676217e-02, 2.2329506e-03, 3.0447412e-03, 1.1478510e-02,
        8.6737014e-03, 2.9291512e-02]], dtype=float32)

## Post-processing

Follow [mewc-predict](https://github.com/zaandahl/mewc-predict/blob/main/src/mewc_predict.py)

In [9]:
with open("../input/train-and-evaluate-terainet/class_list.yaml", "r") as file:
    class_map = yaml.safe_load(file)
class_map

{'1': 'tiger',
 '10': 'bird',
 '2': 'leopard',
 '3': 'black_bear',
 '4': 'other_carnivores',
 '5': 'deer',
 '6': 'wild_boar',
 '7': 'buffalo',
 '8': 'rhino',
 '9': 'elephant'}

In [10]:
inv_class = {v: k for k, v in class_map.items()}
inv_class

{'tiger': '1',
 'bird': '10',
 'leopard': '2',
 'black_bear': '3',
 'other_carnivores': '4',
 'deer': '5',
 'wild_boar': '6',
 'buffalo': '7',
 'rhino': '8',
 'elephant': '9'}

In [11]:
file_paths = img_generator.file_paths
filenames = list(map(lambda x : Path(x).name, file_paths))
labels = list(map(lambda x : Path(x).parent.name, file_paths))

In [12]:
class_ids = sorted(inv_class.values())
class_names = [class_map.get(i,i)  for i in class_ids]
pred_df = pd.DataFrame(preds, columns=class_ids)
pred_df.head()

,1,10,2,3,4,5,6,7,8,9
0,0.052382,0.199962,0.284953,0.046548,0.119749,0.132219,0.018170,0.053616,0.052950,0.039450
1,0.257370,0.109498,0.161220,0.013591,0.084038,0.006860,0.008987,0.075156,0.068466,0.214814
2,0.019460,0.016661,0.090842,0.127973,0.138110,0.037300,0.070162,0.126267,0.331287,0.041939
3,0.774618,0.007588,0.081881,0.041599,0.009033,0.017620,0.020353,0.019009,0.008609,0.019690
4,0.870636,0.005844,0.056552,0.010453,0.018009,0.005671,0.005432,0.013849,0.006193,0.007361

In [13]:
file_series = pd.Series(filenames)
label_series = pd.Series(labels)
pred_df.insert(0, "filename", file_series, True)
pred_df.insert(1, "label", label_series, True)
pred_df = pd.melt(pred_df, id_vars=['filename', 'label'], value_vars=class_ids, var_name="class_id", value_name="prob")
pred_df["class_name"] = pred_df["class_id"].replace(class_map)
pred_df["class_rank"] = pred_df.groupby("filename")["prob"].rank("average", ascending=False)
pred_df.head(10)

                  filename   label class_id      prob class_name  class_rank
0   class_1_test2_11-0.jpg  images        1  0.052382      tiger         7.0
1  class_1_test2_145-0.jpg  images        1  0.257370      tiger         1.0
2  class_1_test2_161-0.jpg  images        1  0.019460      tiger         9.0
3  class_1_test2_180-0.jpg  images        1  0.774618      tiger         1.0
4  class_1_test2_201-0.jpg  images        1  0.870636      tiger         1.0
5   class_1_test2_22-0.jpg  images        1  0.805142      tiger         1.0
6  class_1_test2_234-0.jpg  images        1  0.761445      tiger         1.0
7  class_1_test2_305-0.jpg  images        1  0.000171      tiger        10.0
8  class_1_test2_315-0.jpg  images        1  0.881008      tiger         1.0
9  class_1_test2_318-0.jpg  images        1  0.856423      tiger         1.0

In [14]:
pred_df = pred_df[pred_df["class_rank"] == 1.0]
pred_df = pred_df.drop(["label", "class_rank"], axis=1)
pred_df

                   filename class_id      prob        class_name
1   class_1_test2_145-0.jpg        1  0.257370             tiger
3   class_1_test2_180-0.jpg        1  0.774618             tiger
4   class_1_test2_201-0.jpg        1  0.870636             tiger
5    class_1_test2_22-0.jpg        1  0.805142             tiger
6   class_1_test2_234-0.jpg        1  0.761445             tiger
8   class_1_test2_315-0.jpg        1  0.881008             tiger
9   class_1_test2_318-0.jpg        1  0.856423             tiger
20   class_1_test2_11-0.jpg        2  0.284953           leopard
47  class_1_test2_305-0.jpg        4  0.397291  other_carnivores
82  class_1_test2_161-0.jpg        8  0.331287             rhino