<a href="https://www.kaggle.com/code/alexvmt/terainet-inference-example?scriptVersionId=335791988" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

<a href="https://www.kaggle.com/code/alexvmt/terainet-inference-example?scriptVersionId=247707904" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# TeraiNet inference example

Follow [mewc-predict](https://github.com/zaandahl/mewc-predict/blob/main/src/mewc_predict.py) for the general procedure

## Setup

### Imports

Follow [mewc-flow](https://github.com/zaandahl/mewc-flow/blob/main/requirements.txt) for the key package versions

In [1]:
!pip install keras==3.3.3 kimm==0.2.5 tensorflow==2.16.1

Requirement already satisfied: keras==3.3.3 in /opt/conda/lib/python3.10/site-packages (3.3.3)
Collecting kimm==0.2.5
  Downloading kimm-0.2.5-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: tensorflow==2.16.1 in /opt/conda/lib/python3.10/site-packages (2.16.1)
Requirement already satisfied: absl-py in /opt/conda/lib/python3.10/site-packages (from keras==3.3.3) (1.4.0)
Requirement already satisfied: numpy in /opt/conda/lib/python3.10/site-packages (from keras==3.3.3) (1.26.4)
Requirement already satisfied: rich in /opt/conda/lib/python3.10/site-packages (from keras==3.3.3) (13.7.1)
Requirement already satisfied: namex in /opt/conda/lib/python3.10/site-packages (from keras==3.3.3) (0.0.8)
Requirement already satisfied: h5py in /opt/conda/lib/python3.10/site-packages (from keras==3.3.3) (3.11.0)
Requirement already satisfied: optree in /opt/conda/lib/python3.10/site-packages (from keras==3.3.3) (0.11.0)
Requirement already satisfied: ml-dtypes in /opt/conda/lib/python3.10/site-packages (from keras==3.3.3) (0.3.2)
Requirement already satisfied: astunparse>=1.6.0 in /opt/conda/lib/python3.10/site-packages (from tensorflow==2.16.1) (1.6.3)
Requirement already satisfied: flatbuffers>=23.5.26 in /opt/conda/lib/python3.10/site-packages (from tensorflow==2.16.1) (24.3.25)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /opt/conda/lib/python3.10/site-packages (from tensorflow==2.16.1) (0.5.4)
Requirement already satisfied: google-pasta>=0.1.1 in /opt/conda/lib/python3.10/site-packages (from tensorflow==2.16.1) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /opt/conda/lib/python3.10/site-packages (from tensorflow==2.16.1) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /opt/conda/lib/python3.10/site-packages (from tensorflow==2.16.1) (3.3.0)
Requirement already satisfied: packaging in /opt/conda/lib/python3.10/site-packages (from tensorflow==2.16.1) (21.3)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /opt/conda/lib/python3.10/site-packages (from tensorflow==2.16.1) (3.20.3)
Requirement already satisfied: requests<3,>=2.21.0 in /opt/conda/lib/python3.10/site-packages (from tensorflow==2.16.1) (2.32.3)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.10/site-packages (from tensorflow==2.16.1) (70.0.0)
Requirement already satisfied: six>=1.12.0 in /opt/conda/lib/python3.10/site-packages (from tensorflow==2.16.1) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in /opt/conda/lib/python3.10/site-packages (from tensorflow==2.16.1) (2.4.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /opt/conda/lib/python3.10/site-packages (from tensorflow==2.16.1) (4.12.2)
Requirement already satisfied: wrapt>=1.11.0 in /opt/conda/lib/python3.10/site-packages (from tensorflow==2.16.1) (1.16.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /opt/conda/lib/python3.10/site-packages (from tensorflow==2.16.1) (1.62.2)
Requirement already satisfied: tensorboard<2.17,>=2.16 in /opt/conda/lib/python3.10/site-packages (from tensorflow==2.16.1) (2.16.2)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /opt/conda/lib/python3.10/site-packages (from tensorflow==2.16.1) (0.37.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /opt/conda/lib/python3.10/site-packages (from astunparse>=1.6.0->tensorflow==2.16.1) (0.43.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorflow==2.16.1) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorflow==2.16.1) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorflow==2.16.1) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorflow==2.16.1) (2024.6.2)
Requirement already satisfied: markdown>=2.6.8 in /opt/conda/lib/python3.10/site-packages (from tensorboard<2.17,>=2.16->tensorflow==2.16.1) (3.6)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /opt/conda/lib/python3.10/site-packages (from tensorboard<2.17,>=2.16->tensorflow==2.16.1) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /opt/conda/lib/python3.10/site-packages (from tensorboard<2.17,>=2.16->tensorflow==2.16.1) (3.1.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/conda/lib/python3.10/site-packages (from packaging->tensorflow==2.16.1) (3.1.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/conda/lib/python3.10/site-packages (from rich->keras==3.3.3) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/conda/lib/python3.10/site-packages (from rich->keras==3.3.3) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in /opt/conda/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich->keras==3.3.3) (0.1.2)
Requirement already satisfied: MarkupSafe>=2.1.1 in /opt/conda/lib/python3.10/site-packages (from werkzeug>=1.0.1->tensorboard<2.17,>=2.16->tensorflow==2.16.1) (2.1.5)
Downloading kimm-0.2.5-py3-none-any.whl (123 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.4/123.4 kB 6.0 MB/s eta 0:00:00
Installing collected packages: kimm
Successfully installed kimm-0.2.5

In [2]:
import os
import random
import shutil
from pathlib import Path

import pandas as pd
import tensorflow as tf
import yaml
from keras import saving

### Utilities

In [3]:
def copy_random_images(src_dir, dst_dir, n, seed=42):
    """
    Copies n random images from src_dir to dst_dir.

    Args:
        src_dir (str): Source directory containing images.
        dst_dir (str): Destination directory to copy images into.
        n (int): Number of images to copy.
        seed (int): Random seed for reproducibility.
    """
    # Ensure target directory exists
    os.makedirs(dst_dir, exist_ok=True)

    # List all files in the source directory
    all_files = [f for f in os.listdir(src_dir) if os.path.isfile(os.path.join(src_dir, f))]

    # Check if n is greater than available files
    if n > len(all_files):
        raise ValueError(
            f"Requested {n} images, but only {len(all_files)} available in source directory."
        )

    # Randomly sample n files
    random.seed(seed)
    selected_files = random.sample(all_files, n)

    # Copy each file to the target directory
    for filename in selected_files:
        src_path = os.path.join(src_dir, filename)
        dst_path = os.path.join(dst_dir, filename)
        shutil.copy2(src_path, dst_path)

    print(f"Copied {n} random images from '{src_dir}' to '{dst_dir}'.")

## Prepare images

In [4]:
copy_random_images("../input/preprocess-images/terainet_images/test2/class_1", "../images", 10)

Copied 10 random images from '../input/preprocess-images/terainet_images/test2/class_1' to '../images'.

In [5]:
img_generator = tf.keras.preprocessing.image_dataset_from_directory(
    "../images", labels=None, label_mode=None, batch_size=8, image_size=(224, 224), shuffle=False
)

Found 10 files.

## Predict

In [6]:
model = saving.load_model("../input/train-and-evaluate-terainet/model.keras", compile=False)

In [7]:
preds = model.predict(img_generator)

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1784231672.364827      77 service.cc:145] XLA service 0x7bc8280032b0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1784231672.364898      77 service.cc:153]   StreamExecutor device (0): Tesla P100-PCIE-16GB, Compute Capability 6.0

1/2 ━━━━━━━━━━━━━━━━━━━━ 12s 12s/step

I0000 00:00:1784231679.708629      77 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.

2/2 ━━━━━━━━━━━━━━━━━━━━ 23s 11s/step

In [8]:
preds

array([[0.84674287, 0.02370572, 0.01107171, 0.01372842, 0.01831189,
        0.01507596, 0.02201088, 0.02069564, 0.01198735, 0.01666968],
       [0.00792261, 0.03121234, 0.7617105 , 0.02386605, 0.02557292,
        0.03509789, 0.02906937, 0.01509295, 0.06149056, 0.00896472],
       [0.740985  , 0.06773984, 0.02880301, 0.02516732, 0.03688958,
        0.01440554, 0.02417418, 0.01989504, 0.01772652, 0.024214  ],
       [0.8303648 , 0.02398647, 0.01483363, 0.02067083, 0.02197562,
        0.02233409, 0.01618276, 0.01863491, 0.01590108, 0.01511574],
       [0.72691184, 0.08180103, 0.02423305, 0.03061306, 0.02657528,
        0.03416738, 0.02031484, 0.01013856, 0.02785124, 0.01739373],
       [0.83608437, 0.01838356, 0.01862682, 0.01791963, 0.01226628,
        0.0172498 , 0.02080018, 0.01985842, 0.0206185 , 0.01819235],
       [0.02452771, 0.03081482, 0.14634302, 0.68820685, 0.0199675 ,
        0.03976144, 0.01232851, 0.00597061, 0.01715526, 0.01492433],
       [0.04067608, 0.19861075, 0.05725198, 0.59585863, 0.0099168 ,
        0.00657889, 0.0039429 , 0.01554443, 0.01902047, 0.05259907],
       [0.84734815, 0.02227532, 0.0131381 , 0.01817557, 0.01092368,
        0.00981132, 0.02361056, 0.01625736, 0.02945238, 0.00900752],
       [0.7740536 , 0.04197433, 0.02039657, 0.02165647, 0.0338989 ,
        0.02132377, 0.02433175, 0.02990053, 0.0143321 , 0.01813191]],
      dtype=float32)

## Post-processing

Follow [mewc-predict](https://github.com/zaandahl/mewc-predict/blob/main/src/mewc_predict.py)

In [9]:
with open("../input/train-and-evaluate-terainet/class_list.yaml", "r") as file:
    class_map = yaml.safe_load(file)
class_map

{'1': 'tiger',
 '10': 'bird',
 '2': 'leopard',
 '3': 'black_bear',
 '4': 'other_carnivores',
 '5': 'deer',
 '6': 'wild_boar',
 '7': 'buffalo',
 '8': 'rhino',
 '9': 'elephant'}

In [10]:
inv_class = {v: k for k, v in class_map.items()}
inv_class

{'tiger': '1',
 'bird': '10',
 'leopard': '2',
 'black_bear': '3',
 'other_carnivores': '4',
 'deer': '5',
 'wild_boar': '6',
 'buffalo': '7',
 'rhino': '8',
 'elephant': '9'}

In [11]:
file_paths = img_generator.file_paths
filenames = list(map(lambda x: Path(x).name, file_paths))
labels = list(map(lambda x: Path(x).parent.name, file_paths))

In [12]:
class_ids = sorted(inv_class.values())
class_names = [class_map.get(i, i) for i in class_ids]
pred_df = pd.DataFrame(preds, columns=class_ids)
pred_df.head()

,1,10,2,3,4,5,6,7,8,9
0,0.846743,0.023706,0.011072,0.013728,0.018312,0.015076,0.022011,0.020696,0.011987,0.016670
1,0.007923,0.031212,0.761711,0.023866,0.025573,0.035098,0.029069,0.015093,0.061491,0.008965
2,0.740985,0.067740,0.028803,0.025167,0.036890,0.014406,0.024174,0.019895,0.017727,0.024214
3,0.830365,0.023986,0.014834,0.020671,0.021976,0.022334,0.016183,0.018635,0.015901,0.015116
4,0.726912,0.081801,0.024233,0.030613,0.026575,0.034167,0.020315,0.010139,0.027851,0.017394

In [13]:
file_series = pd.Series(filenames)
label_series = pd.Series(labels)
pred_df.insert(0, "filename", file_series, True)
pred_df.insert(1, "label", label_series, True)
pred_df = pd.melt(
    pred_df,
    id_vars=["filename", "label"],
    value_vars=class_ids,
    var_name="class_id",
    value_name="prob",
)
pred_df["class_name"] = pred_df["class_id"].replace(class_map)
pred_df["class_rank"] = pred_df.groupby("filename")["prob"].rank("average", ascending=False)
pred_df.head(10)

                  filename   label class_id      prob class_name  class_rank
0  class_1_test2_118-0.jpg  images        1  0.846743      tiger         1.0
1  class_1_test2_135-0.jpg  images        1  0.007923      tiger        10.0
2  class_1_test2_143-0.jpg  images        1  0.740985      tiger         1.0
3  class_1_test2_185-0.jpg  images        1  0.830365      tiger         1.0
4   class_1_test2_19-0.jpg  images        1  0.726912      tiger         1.0
5  class_1_test2_210-0.jpg  images        1  0.836084      tiger         1.0
6  class_1_test2_283-0.jpg  images        1  0.024528      tiger         5.0
7    class_1_test2_3-0.jpg  images        1  0.040676      tiger         5.0
8  class_1_test2_310-0.jpg  images        1  0.847348      tiger         1.0
9   class_1_test2_75-0.jpg  images        1  0.774054      tiger         1.0

In [14]:
pred_df = pred_df[pred_df["class_rank"] == 1.0]
pred_df = pred_df.drop(["label", "class_rank"], axis=1)
pred_df

                   filename class_id      prob  class_name
0   class_1_test2_118-0.jpg        1  0.846743       tiger
2   class_1_test2_143-0.jpg        1  0.740985       tiger
3   class_1_test2_185-0.jpg        1  0.830365       tiger
4    class_1_test2_19-0.jpg        1  0.726912       tiger
5   class_1_test2_210-0.jpg        1  0.836084       tiger
8   class_1_test2_310-0.jpg        1  0.847348       tiger
9    class_1_test2_75-0.jpg        1  0.774054       tiger
21  class_1_test2_135-0.jpg        2  0.761711     leopard
36  class_1_test2_283-0.jpg        3  0.688207  black_bear
37    class_1_test2_3-0.jpg        3  0.595859  black_bear